#!/bin/bash

#PBS -l nodes=1
#PBS -l walltime=10:00:00
# PBS -j oe
#PBS -m ae
#PBS -M rl6sf@virginia.edu

U=$HOME/scratch/set_i/hg19.bed
BED_DIR=$HOME/scratch/set_i/exp

SEQ=$HOME/src/set_intersection/sequential
COUNT=num_sim_scan_seq

#echo "$COUNT $i"

for BED_A in $BED_DIR/*.bed
do
	for BED_B in $BED_DIR/*.bed
	do
		if [ "$BED_A" != "$BED_B" ]
		then
			$SEQ/$COUNT $U $BED_A $BED_B 10000
		fi
	done
done
