#!/bin/bash

source $HOME/src/set_intersection/tests/files.sh

$BIG_COUNT_BSEARCH_SEQ $U $KIL_A $KIL_B 100
$BIG_COUNT_BSEARCH_SEQ $U $TEN_KIL_A $TEN_KIL_B 1000
$BIG_COUNT_BSEARCH_SEQ $U $HUND_KIL_A $HUND_KIL_B 10000
$BIG_COUNT_BSEARCH_SEQ $U $MIL_A $MIL_B 100000
#$BIG_COUNT_BSEARCH_SEQ $U $TEN_MIL_A $TEN_MIL_B 1000
