#!/bin/bash

source $HOME/src/set_intersection/tests/files.sh


#$COUNT_BSEARCH_OMP $U $KIL_A $KIL_B 1
#$COUNT_BSEARCH_OMP $U $TEN_KIL_A $TEN_KIL_B 1
#$COUNT_BSEARCH_OMP $U $HUND_KIL_A $HUND_KIL_B 1
#$COUNT_BSEARCH_OMP $U $HUND_KIL_A $HUND_KIL_B 
$COUNT_BSEARCH_OMP $U $MIL_A $MIL_B 1
$COUNT_BSEARCH_OMP $U $MIL_A $MIL_B 2
$COUNT_BSEARCH_OMP $U $MIL_A $MIL_B 3
$COUNT_BSEARCH_OMP $U $MIL_A $MIL_B 4
$COUNT_BSEARCH_OMP $U $MIL_A $MIL_B 5
$COUNT_BSEARCH_OMP $U $MIL_A $MIL_B 6
$COUNT_BSEARCH_OMP $U $MIL_A $MIL_B 7
$COUNT_BSEARCH_OMP $U $MIL_A $MIL_B 8
