#!/bin/bash

source $HOME/src/set_intersection/tests/files.sh

CMD=$SEQ_BASE/count_sweep_seq
BRUTE=$SEQ_BASE/count_brute_force_seq

#echo $SIMPLE_REPEATS
#$CMD $U $A $A 1 1024
#$CMD $U $A $A 2 1024
#$CMD $U $A $A 3 1024
#$CMD $U $A $A 4 1024
$CMD $U $KIL_A $KIL_B
$CMD $U $TEN_KIL_A $TEN_KIL_B
$CMD $U $HUND_KIL_A $HUND_KIL_B
$CMD $U $MIL_A $MIL_B
$CMD $U $TEN_MIL_A $TEN_MIL_B
#$CMD $U $SIMPLE_REPEATS $SIMPLE_REPEATS 5 1024
#$CMD $U $SIMPLE_REPEATS $SIMPLE_REPEATS 4 1024
#$CMD $U $SIMPLE_REPEATS $SIMPLE_REPEATS 3 1024
#$CMD $U $SIMPLE_REPEATS $SIMPLE_REPEATS 2 1024
#$CMD $U $KIL_A $KI 10000 1 1 0
