#!/bin/bash

source $HOME/src/set_intersection/tests/files.sh


#$COUNT_BSEARCH_OMP $U $KIL_A $KIL_B 1
#$COUNT_BSEARCH_OMP $U $TEN_KIL_A $TEN_KIL_B 1
#$COUNT_BSEARCH_OMP $U $HUND_KIL_A $HUND_KIL_B 1
#$COUNT_BSEARCH_OMP $U $HUND_KIL_A $HUND_KIL_B 
