#!/bin/bash

source $HOME/src/set_intersection/tests/files.sh

REPS=1000

#$SIM_BSEARCH_GM_CUDA $U $KIL_A $KIL_B $REPS 1 1024 0
#$SIM_BSEARCH_GM_CUDA $U $TEN_KIL_A $TEN_KIL_B $REPS 1 1024 0
#$SIM_BSEARCH_GM_CUDA $U $HUND_KIL_A $HUND_KIL_B $REPS 1 1024 0
#$SIM_BSEARCH_GM_CUDA $U $MIL_A $MIL_B $REPS 1 1024 0
#$SIM_BSEARCH_GM_CUDA $U $TEN_MIL_A $TEN_MIL_B $REPS 1 1024 0
#$SIM_BSEARCH_SEQ $U $A $B $REPS
#$COUNT_BRUTE_SEQ $U $A $B

$SIM_BSEARCH_GM_CUDA $U $A $A_a $REPS 1 1024 0
$SIM_BSEARCH_OMP $U $A $A_a $REPS 7
echo
$SIM_BSEARCH_GM_CUDA $U $A $A_b $REPS 1 1024 0
$SIM_BSEARCH_OMP $U $A $A_b $REPS 7
echo
$SIM_BSEARCH_GM_CUDA $U $A_a $A_b $REPS 1 1024 0
$SIM_BSEARCH_OMP $U $A_a $A_b $REPS 7
