#!/bin/bash

source $HOME/src/set_intersection/tests/files.sh

$SIM_BSEARCH_SEQ $U $KIL_A $KIL_B 100
$SIM_BSEARCH_SEQ $U $TEN_KIL_A $TEN_KIL_B 100
$SIM_BSEARCH_SEQ $U $HUND_KIL_A $HUND_KIL_B 100
#$COUNT_BSEARCH_SEQ $U $MIL_A $MIL_B 1000
#$COUNT_BSEARCH_SEQ $U $TEN_MIL_A $TEN_MIL_B

#$COUNT_BRUTE_SEQ $TINY_U $TINY_A $TINY_B
#$COUNT_SWEEP_SEQ $TINY_U $TINY_A $TINY_B
#$COUNT_BSEARCH_SEQ $TINY_U $TINY_A $TINY_B
