EXECUTABLE	:= order
# Cuda source files (compiled with nvcc)
CUFILES		:= order.cu radixsort.cu random.cu
# C++ source files (compiled with gcc)
CCFILES		:= radixsort.cpp bed.c

USECUDPP	:= 1

################################################################################
# Rules and targets

include ../../common/common.mk

